import { Analysis, MarketAnalysis, Insight ,AnalyticalPerformance} from './types';
export const ANALYTICAL_PERFORMANCE: AnalyticalPerformance = {
  publishedAnalysis:1,
  validated: 1,
  invalidated: 0,
  validationAccuracy: "Not statiscally meaningful (early stage dataset)", // percentage
  averageReactionRange: 0, // percentage
};
export const MOCK_Analysis: Analysis[] = [
     {
    asset: "commodities",
    pair: "XAUUSD",
    tf: "-4H",
    bias: "bearish",
    initialforecast: "Bearish Delivery: 4,595 to 4,468 → 4,024",
    observedoutcome: "Market Delivery: 4,380 → 3,965",
    validationstatus: "NEUTRAL",
    reactionmagnitude:"~9.5% Bearish Move",
    result: "NEUTRAL",
    beforeImage: "https://www.tradingview.com/x/cDJvBDLZ/",
    afterImage: "https://www.tradingview.com/x/CE7rybiS/",
    description: "Price ultimately moved lower in line with the broader bearish framework outlined in the initial analysis; however, the anticipated corrective advance failed to reach the identified resistance zone that had been highlighted as the primary decision point. Instead, selling pressure emerged earlier than expected, causing the market to rotate lower before a complete interaction with the proposed reaction area could occur.The recovery from the liquidity sweep remained corrective in nature and lacked strong bullish momentum, but the absence of a full test of resistance leaves the proposed rejection scenario unconfirmed. As a result, the outcome remains neutral from a validation perspective. While downside continuation aligned with the broader directional bias, the key resistance objective was not fulfilled, leaving the original thesis neither fully validated nor invalidated.Outcome Summary:Price rotated lower before reaching the projected resistance zone. The broader bearish direction remained intact, but without interaction at the identified decision point, the initial thesis remains neutral in outcome.",
    date: "2026-06-24",
    datepub: "2026-06-17",
  },
 {
    asset: "crypto",
    pair: "BTCUSD",
    tf: "-1D",
    bias: "bearish",
    initialforecast: "Bearish Delivery: 84,000 to 81,000 → 60,000",
    observedoutcome: "Market Delivery: 82,800 → 59,150",
    validationstatus: "VALIDATED",
    reactionmagnitude:"~25% Bearish Move",
    result: "VALIDATED",
    beforeImage: "https://www.tradingview.com/x/gb3wKk6s/",
    afterImage: "https://www.tradingview.com/x/hxLdtTUa/",
    description: "The anticipated reaction from the rejection block played out as expected, validating the bearish scenario outlined in the original analysis. After reaching the identified resistance zone, price failed to establish acceptance above the rejection block and instead showed clear selling pressure, confirming that supply remained active within the area. The advance into resistance lacked the impulsive strength required for a bullish continuation and ultimately resulted in a sharp downside expansion. This reaction reinforced the view that the preceding upward movement was corrective in nature rather than the beginning of a sustained bullish trend. As sellers regained control, market structure shifted lower and momentum accelerated to the downside. Following the rejection, price moved aggressively toward the previously identified liquidity area, successfully reaching and sweeping the liquidity resting beneath the range. The liquidity objective highlighted in the initial thesis has now been fulfilled, demonstrating how the market utilized the resistance zone as a distribution area before seeking liquidity at lower levels. The selloff into liquidity was characterized by strong bearish displacement, indicating conviction from market participants and confirming the significance of the rejection block as the origin of the move. With the targeted liquidity now taken, the market has reached an important reaction zone where participants will be monitoring for signs of absorption, consolidation, or continuation. Outcome Summary:The bearish thesis was validated as price rejected from the identified rejection block, failed to sustain higher prices, and delivered the projected move into the liquidity area below. The key resistance zone successfully acted as the decision point for the market, while the targeted liquidity objective was achieved, completing the primary scenario outlined in the original analysis.",
    date: "2026-05-04",
    datepub: "2026-06-09",
  },
];

export const MARKET_ANALYSIS: MarketAnalysis[] = [
  {
    id: "a8",
    asset: "commodities",
    pair: "XAUUSD",
    tf: "-4H",  
    conditions:"NULL",
    bias: "bearish",
    status: "Active",
    image: "https://www.tradingview.com/x/yPtkbOvF/",
    date: "2026-07-7",
    title:"XAUUSD Approaches Key 4H Central Zone & Rejection Block Confluence",
    description: "I observed a clear shift in market structure following a strong impulsive bearish move that established lower highs and lower lows across the 4-hour timeframe. Price reacted sharply from a previously established resistance region, confirming continued selling pressure and initiating a downside expansion. Following the impulsive decline, the market transitioned into a corrective phase, where price began recovering from recent lows.During this phase, price developed a gradual ascending structure while consistently creating higher lows. This recovery appears corrective rather than impulsive, suggesting that the movement is driven more by rebalancing and liquidity seeking rather than sustained bullish strength. The steady advance toward higher prices indicates that the market is revisiting important technical areas before determining its next directional move.Currently, price is approaching a previously established Central Zone, which acts as the first key resistance area. Above this region lies the Rejection Block + FVGs confluence, which represents a higher timeframe resistance zone and a significant area of interest for market participants. The approach into these zones lacks strong impulsive conviction and appears relatively controlled, which often precedes a reaction rather than continuation.Speculative Outlook:Price is now entering a critical resistance region, making this an important decision point for the market. If bearish candlestick patterns or rejection behavior develops within the Central Zone, it would indicate that sellers are stepping back in, potentially leading to another downside move toward lower support.There is also a possibility of a liquidity grab above the Central Zone, where price briefly breaks into the Rejection Block + FVGs confluence, captures resting buy-side liquidity, and then reverses to the downside. Such a scenario would further strengthen the bearish bias.However, if price manages to sustain above both the Central Zone and the Rejection Block + FVGs confluence with strong impulsive bullish candles, it would invalidate the immediate bearish outlook and suggest a shift toward continuation. Until that confirmation appears, the current structure favors monitoring these resistance zones for a potential bearish reaction.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
      {
    id: "a7",
    asset: "commodities",
    pair: "XAUUSD",
    tf: "-1W",  
    conditions:"NULL",
    bias: "bullish",
    status: "Active",
    image: "https://www.tradingview.com/x/wlPKUa8g/",
    date: "2026-07-7",
    title:"XAUUSD Approaching a Key Weekly Potential Zone After an Extended Corrective Decline",
    description: "I observed a clear shift in market structure following a prolonged corrective decline that developed after a strong impulsive bullish expansion. Price initially established a series of higher highs and higher lows before gradually losing momentum, allowing sellers to regain control and transition the market into a sustained corrective phase. As the decline progressed, price continued respecting a descending resistance trendline, confirming that bearish pressure remained in control throughout the correction.During this phase, price developed a sequence of lower highs while steadily approaching a previously identified Potential Zone. This movement appears controlled rather than impulsive, suggesting that the market is gradually rebalancing as it approaches a higher timeframe area of interest. The continued respect of the descending resistance indicates that buyers have yet to regain meaningful control despite the slowing momentum.Currently, price is approaching the previously established Potential Zone, which acts as a key support region. This area is significant as it represents a higher timeframe location where market participants may begin responding following the extended corrective decline. The approach toward this zone remains relatively measured, making it an important technical area to monitor for a potential shift in order flow.Speculative Outlook: Price is now entering a critical Potential Zone, making this an important decision point for the market. If bullish candlestick patterns or rejection behavior develops within this region, it would indicate renewed buying interest, potentially leading to a higher timeframe recovery while maintaining respect for the broader market structure.There is also a possibility of a liquidity sweep below the Potential Zone, where price briefly trades beneath the support, captures resting sell-side liquidity, and then reverses to the upside. Such a scenario would further strengthen the probability of a bullish recovery from this higher timeframe region.However, if price fails to hold within the Potential Zone and begins closing decisively below it, the probability of continued downside expansion would increase. Until such confirmation appears, the current structure supports monitoring this key support region for a potential bullish reaction.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
    {
    id: "a6",
    asset: "forex",
    pair: "NZDUSD",
    tf: "-1D",  
    conditions:"NULL",
    bias: "bearish",
    status: "Active",
    image: "https://www.tradingview.com/x/qOWiutXp/",
    date: "2026-07-03",
    title:"Rejection at the Central Zone in NZDUSD or Continuation Higher at 1D",
    description: "I observed a clear shift in market structure following a strong impulsive bearish move that originated after price failed to sustain above a previously established central zone. Price reacted sharply from this area, confirming the presence of strong selling pressure and initiating a downside expansion. Following the impulsive decline, the market transitioned into a corrective phase, where price began recovering from recent lows.During this phase, price developed a gradual ascending structure while consistently creating higher lows. This movement appears corrective rather than impulsive, suggesting that it is driven more by rebalancing and liquidity engineering rather than sustained bullish strength. The recovery toward higher prices indicates that the market is revisiting a significant technical area before determining its next directional move.Currently, price is approaching the previously established Central Zone, which acts as a key resistance area. This region is significant as it has repeatedly influenced price behavior throughout the current market structure, making it a high-probability reaction point. The approach toward this zone lacks strong impulsive conviction and appears relatively controlled, which often precedes a reaction rather than continuation.Speculative Outlook: Price is now entering a critical Central Zone, making this an important decision point for the market. If bearish candlestick patterns or rejection behavior develops within this region, it would indicate that sellers are stepping back in, potentially leading to another downside move toward lower support.There is also a possibility of a liquidity grab above the Central Zone, where price briefly breaks the resistance, captures resting buy-side liquidity, and then reverses to the downside. This scenario would further strengthen the bearish bias.However, if price manages to sustain above the Central Zone with strong impulsive bullish candles, it would invalidate the immediate bearish outlook and suggest a shift toward continuation. Until that confirmation appears, the current structure favors a bearish reaction from this key resistance zone.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
  {
    id: "a5",
    asset: "forex",
    pair: "AUDUSD",
    tf: "-4H",  
    conditions:"NULL",
    bias: "bearish",
    status: "Active",
    image: "https://www.tradingview.com/x/v43LExqw/",
    date: "2026-07-03",
    title:"AUDUSD Approaching a Key Resistance Confluence Following Bearish Expansion at 4H",
    description: "I observed a clear shift in market structure following a strong impulsive bearish move that originated after the formation of a well-defined liquidity zone. Price reacted sharply from this area, confirming the presence of strong selling pressure and initiating a downside expansion. Following the impulsive decline, the market transitioned into a corrective phase, where price began recovering from recent lows.During this phase, price developed a gradual ascending structure while consistently creating higher lows. This movement appears corrective rather than impulsive, suggesting that it is driven more by rebalancing and liquidity engineering than sustained bullish strength. The recovery toward higher prices indicates that the market is revisiting a significant technical area before determining its next directional move.Currently, price is approaching a previously established resistance confluence consisting of a Major Liquidity Zone, S.R Interchange, and an Inner Resistance region. This area is significant as it represents the origin of the last strong bearish expansion, making it a high-probability reaction point. The approach toward this zone lacks strong impulsive conviction and appears relatively controlled, which often precedes a reaction rather than continuation.Speculative Outlook: Price is now entering a critical resistance confluence, making this an important decision point for the market. If bearish candlestick patterns or rejection behavior develops within this region, it would indicate that sellers are stepping back in, potentially leading to another downside move toward lower support.There is also a possibility of a liquidity grab above the resistance zone, where price briefly breaks into the Inner Resistance region, captures resting buy-side liquidity, and then reverses to the downside. Such a scenario would further strengthen the bearish bias.However, if price manages to sustain above the resistance confluence with strong impulsive bullish candles, it would invalidate the immediate bearish outlook and suggest a shift toward continuation. Until that confirmation appears, the current structure favors a bearish reaction from this key resistance region.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
   {
    id: "a4",
    asset: "crypto",
    pair: "BTCUSD",
    tf: "-4H",  
    conditions:"NULL",
    bias: "bearish",
    status: "Active",
    image: "https://www.tradingview.com/x/M6Vpjm1l/",
    date: "2026-07-03",
    title:"BTCUSD Retesting a Key S.R Interchange Zone at 4H",
    description: "I observed a clear shift in market structure following a strong impulsive bearish move that established lower highs and lower lows across the 4-hour timeframe. Price reacted sharply from a previously established resistance region, confirming continued selling pressure and initiating a downside expansion. Following the impulsive decline, the market transitioned into a corrective phase, where price began recovering toward a previously broken support level.During this phase, price developed a gradual bullish retracement while respecting short-term higher lows. This recovery appears corrective rather than impulsive, suggesting that the movement is driven more by rebalancing and liquidity seeking rather than sustained bullish strength. The steady advance toward resistance indicates that the market is revisiting an important technical area before determining its next directional move.Currently, price is approaching a previously established S.R Interchange zone, which now acts as a key resistance area. This region is significant as it represents a former support level that has transitioned into resistance following the bearish market structure shift. The approach into this zone lacks strong impulsive conviction and appears relatively controlled, which often precedes a reaction rather than continuation.Speculative Outlook: Price is now entering a critical S.R Interchange zone, making this a decision point for the market. If bearish candlestick patterns or rejection behavior develops within this region, it would indicate that sellers are stepping back in, potentially leading to another downside move toward lower support.There is also a possibility of a liquidity grab above the S.R Interchange zone, where price briefly breaks the resistance, attracts breakout buyers, and then reverses to the downside. This scenario would further strengthen the bearish bias.However, if price manages to sustain above the S.R Interchange zone with strong impulsive bullish candles, it would invalidate the immediate bearish outlook and suggest a shift toward continuation. Until that confirmation appears, the current structure favors a bearish reaction from this key resistance zone.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
  {
    id: "a3",
    asset: "crypto",
    pair: "BTCUSD",
    tf: "-1W",
    conditions:"NULL",
    bias: "bullish",
    status: "Active",
    image: "https://www.tradingview.com/x/bhQGX3xG/",
    date: "2026-06-26",
    title:"BTCUSD Holding a Key Weekly Rejection Block and Liquidity Gravity Zone",
    description: "I observed a strong bullish expansion following the formation of a liquidity gravity zone, where price initially developed a base before accelerating sharply to the upside, establishing higher highs and higher lows. This impulsive advance was driven by sustained buying pressure and eventually carried BTCUSD into new all-time high territory. After reaching these elevated levels, the market gradually transitioned into a corrective phase, delivering lower highs and lower lows while retracing toward previously established areas of interest.As price declined, it approached a significant higher timeframe support region consisting of a Rejection Block and an embedded Fair Value Gap. This confluence represents the primary area of interest and serves as a technically significant support region, as it aligns with the origin of the prior impulsive expansion and previously inefficient price delivery. Beneath this region lies an Order Flow zone, which may provide additional support should price extend slightly lower before establishing acceptance.Currently, price is approaching this previously established support confluence, which acts as a key decision zone for the market. This area is significant as it represents the origin of the prior impulsive expansion. The decline into this region has been relatively controlled and appears corrective rather than impulsive, a characteristic often associated with testing higher timeframe support rather than immediate continuation. While the Rejection Block and Fair Value Gap remain the preferred area for a reaction, the underlying Order Flow zone may still provide support if a deeper test occurs.Speculative Outlook: Price is now entering a critical higher timeframe support region, making this an important decision point for the market. If bullish candlestick patterns or rejection behavior develops within the support confluence, it would indicate renewed demand, potentially leading to a higher timeframe recovery.There is also a possibility of a liquidity grab below the primary support zone, where price briefly trades into the underlying Order Flow area, captures resting sell-side liquidity, and then reverses to the upside. Such a scenario would further reinforce the probability of a higher timeframe recovery.However, if price fails to hold within this support confluence and begins closing decisively below it, the probability of continued downside expansion would increase. Until such confirmation appears, the current market structure continues to support the possibility of a bullish reaction from this key higher timeframe support region.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
  {
    id: "a2",
    asset: "commodities",
    pair: "XAUUSD",
    tf: "-4H",
    conditions:"NULL",
    bias: "bearish",
    status: "Completed",
    image: "https://www.tradingview.com/x/cDJvBDLZ/",
    date: "2026-06-17",
    title:"Liquidity Formation Following Bearish Expansion in XAUUSD",
    description: "I observed a clear shift in market structure following a strong impulsive bearish move that originated from a well-defined support-to-resistance region. Price reacted aggressively from this zone, confirming the presence of strong supply and initiating a downside expansion. After the impulsive decline, the market transitioned into a corrective phase, following a sweep of liquidity beneath recent lows.During this phase, price developed a recovery structure while respecting the liquidity low as a foundation. The advance has been relatively controlled, forming short-term higher lows; however, the overall movement appears corrective rather than impulsive. This suggests that the move is driven more by rebalancing and liquidity engineering rather than strong bullish intent.The liquidity formed near the lows indicates the presence of resting orders, which the market has already interacted with before initiating the current recovery. Despite this, the structure lacks the displacement and momentum typically required to confirm a sustained bullish reversal.Currently, price is approaching a short-term resistance area formed during the previous bearish expansion. This zone acts as a key reaction point, as it represents an area where supply previously entered the market. The approach toward this level remains relatively measured and lacks strong bullish conviction, which often increases the probability of a reaction rather than continuation.Speculative Outlook:Price is now testing a critical resistance region, making this a decision point for the market. If rejection behavior or bearish candlestick patterns develop within this zone, it would indicate that sellers are re-entering, potentially leading to another move lower targeting the liquidity area below.There is also a possibility of a liquidity grab above this resistance, where price briefly trades beyond the zone to capture buy-side liquidity before reversing to the downside. Such a move would further reinforce the bearish bias.However, if price manages to sustain above this resistance with strong impulsive bullish candles and clear follow-through, it would weaken the immediate bearish outlook and indicate broader structural recovery. Until such confirmation appears, the current price action favors a corrective rally within a bearish framework.",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
    {
    id: "a1",
    asset: "crypto",
    pair: "BTCUSD",
    tf: "-1D",
    conditions:"NULL",
    bias: "bearish",
    status: "Completed",
    image: "https://www.tradingview.com/x/gb3wKk6s/",
    date: "2026-05-04",
    title:"Rejection at Key Resistance with Liquidity Formation in BTCUSD",
    description: "I observed a clear shift in market structure following a strong impulsive bearish move that originated from a well-defined rejection block. Price reacted sharply from this zone, confirming the presence of strong supply and initiating a downside expansion. After the impulsive drop, the market transitioned into a corrective phase, where price began forming a base within a defined liquidity area.\nDuring this phase, price developed a gradual ascending structure, respecting a short-term trendline while consistently creating higher lows. This movement appears corrective rather than impulsive, suggesting that it is driven more by rebalancing and liquidity engineering rather than strong bullish intent. The liquidity formed within this range indicates resting orders, which the market may use before the next directional move.\nCurrently, price is approaching the previously established rejection block, which acts as a key resistance zone. This area is significant as it was the origin of the last strong bearish impulse, making it a high-probability reaction point. The approach toward this zone lacks strong impulsive conviction and appears relatively controlled, which often precedes a reaction rather than continuation.\nSpeculative Outlook: Price is now entering a critical rejection block, making this a decision point for the market. If bearish candlestick patterns or rejection behavior forms within this zone, it would indicate that sellers are stepping back in, potentially leading to another downside move targeting the liquidity area below.\nThere is also a possibility of a liquidity grab above the rejection block, where price briefly breaks the zone to capture resting buy-side liquidity before reversing to the downside. This scenario would further strengthen the bearish bias.\nHowever, if price manages to sustain above the rejection block with strong impulsive bullish candles, it would invalidate the immediate bearish outlook and suggest a shift toward continuation. Until that confirmation appears, the current structure favors a bearish reaction from this key resistance zone. ",
    disclaimer: "NOT INVESTMENT ADVICE-RESEARCH ONLY.",
  },
  // {
  //   id: "a2",
  //   asset: "forex",
  //   pair: "XAUUSD",
  //   tf: "-H4",
  //   conditions:"NULL",
  //   bias: "bullish",
  //   status: "Active",
  //   image: "https://www.tradingview.com/x/hYJTeBhy/",
  //   date: "2024-03-12",
  //   title:"Supply Rejection in XAUUSD After V-Shaped Recovery",
  //   description: "I observed a strong bearish move followed by a sharp recovery, where price formed a V-shaped reaction from lower levels, indicating aggressive demand stepping in after the sell-off. However, after this recovery, price failed to continue making higher highs and instead began to stall near a defined resistance zone. This behavior suggests that the upward move was corrective rather than a full reversal, as supply started to absorb buying pressure.As the structure developed, price formed a lower high within the resistance zone and began to rotate downward, confirming weakness. The inability to break and sustain above this zone indicates that sellers remain in control at higher levels. The recent candles show a gradual decline, forming a short-term bearish structure with lower highs.Currently, price is moving away from the resistance zone and heading toward lower levels, with momentum shifting back in favor of sellers.Speculative Outlook:Price is now rejecting from a key supply zone, which acts as a critical decision area. If this rejection continues, the market may extend its bearish move toward lower support zones.There is also a possibility of a minor pullback back into the supply zone, followed by continuation downward, maintaining the bearish structure.However, if price manages to break above this resistance zone with strong bullish momentum, it would invalidate the bearish outlook and suggest a potential reversal. This makes the current area a key decision point between continuation of the downtrend or a shift toward bullish recovery."
  // },
];

export const INSIGHTS: Insight[] = [
  {
    title: "Chart Patterns",
    text: "Serve as structural zones for assessing supply-demand interaction and liquidity distribution, reflecting phases of accumulation and distribution within market structure.",
  },
  {
    title: "Supply / Demand",
    text: "Defines key price zones where historical order imbalance creates conditions for potential reversal or structural reaction.",
  },
  {
    title: "Candlestick Patterns",
    text: "Provide micro-structural confirmation of market behavior, reflecting short-term shifts in order flow and validating structural responses.",
  },
    {
    title: "CHoCH (Change of Character)",
    text: "Represents a structural indication of potential transition in prevailing market behavior, signaling weakening of prior directional efficiency.",
  },
   {
    title: "BOS (Break of Structure)",
    text: "Represents continuation of established directional flow following structural displacement and resolution of prior inefficiencies.",
  },
  {
    title: "Liquidity",
    text: "Represents areas of concentrated resting interest where price is naturally drawn, functioning as a mechanism for expansion, absorption, or redistribution."
  },
];
