name: Build & Deploy

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - run: npm run build

      - name: Trigger Vercel Deploy
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
